directory: ~/music/beets
library: ~/data/musiclibrary.db
plugins: discogs ftintitle edit mpdupdate fetchart embedart
duplicate_action: keep
ftintitle:
    auto: yes
    drop: no
    format: (feat. {0})
edit:
    itemfields: track title artist album composer
embedart:
    compare_threshold: 7
    maxwidth: 200
